### ISSUE TITLE
Natdevice natcorder error

### ISSUE THREAD

**Issue by jayp84847** [natsuite/NatReader#18]
I am using natdevice and natcorder for my project. It was working with natcorder but after adding natdevice, building for android it shows error "Found plugins with same names, Assets/.../.../.../NatRender.aar"    
When I deleted NatCorder's NatRender recording not working and when I deleted Natdevice's NatRender natdevice not working. Can u help me in this error.

**Comment by olokobayusuf** [comment]
Hi there @jayp84847 . What versions of NatCorder and NatDevice are you using (you can check by looking at the `Changelog.md` files). The latest version of NatCorder and NatDevice use the same build of NatRender. The next updates of both API's will no longer use NatRender.

**Comment by jayp84847** [comment]
Am using latest version of both.

**Comment by jayp84847** [comment]
What's the solution for this?

**Comment by olokobayusuf** [comment]
[Email me](mailto:yusuf@natsuite.io) with your NatCorder invoice number and I'll share the latest version that you can use with NatDevice.

**Comment by jayp84847** [comment]
Where can I found that number?

**Comment by olokobayusuf** [comment]
On the Unity Asset Store. It should show you the invoice or order number on your list of past purchases.

**Comment by jayp84847** [comment]
Ok

**Comment by olokobayusuf** [comment]
Closing this issue.
