### ISSUE TITLE
MP4Reader : EntryPointNotFoundException

### ISSUE THREAD

**Issue by dsmtE** [natsuite/NatReader#19]
Hello,
I'm using **NatReader** and **NatCoder** as transcoding routine to apply effect on previous recorded video (using also NatCoder).
But I have this problem and I am unable to continue with NatReader ...
```csharp
EntryPointNotFoundException: NRCreateMP4Reader
NatSuite.Readers.MP4Reader..ctor (System.String path) (at Library/PackageCache/com.natsuite.natreader@2670b4f751/Runtime/MP4Reader.cs:57)
```
How can i solve this issue ?
Thanks in advance.

**Comment by olokobayusuf** [comment]
Hey @dsmtE , what OS (and version) are you running on?

**Comment by dsmtE** [comment]
Thanks @olokobayusuf  for your reactivity, I am on win 10 (version 19042.867) with Unity in version 2020.2.6f1. I try to build for Android support (api version 24) in Unity. Do you need any other information?

**Comment by olokobayusuf** [comment]
> Thanks @olokobayusuf for your reactivity, I am on win 10 (version 19042.867) with Unity in version 2020.2.6f1. I try to build for Android support (api version 24) in Unity. Do you need any other information?

Ah that's why. NatReader is still pre-release because the Windows backend has not been implemented. See #4

**Comment by dsmtE** [comment]
Thank you, I didn't see this information.
I hope it will be possible soon.
